apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-pv
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  storageClassName: test-pv
  capacity:
    storage: 5.0Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    db: mongo
spec:
  storageClassName: test-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4.9Gi