apiVersion: v1
kind: Service
metadata:
  name: nlp-mongodb
  labels:
    db: mongo
spec:
  type: NodePort
  ports:
  - name: mongo-port
    port: 27017
    targetPort: 27017
  selector:
    db: mongo
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nlp-mongodb
  labels:
    db: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
      - image: mongo:latest
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      restartPolicy: Always


